spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: o-library
  datasource:
    url: ${MYSQL_SERVER_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME}
    platform: ${MYSQL_PLATFORM}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}
  error:
    path: /error
  servlet:
    session:
      timeout: 1440m
# Logger Properties
logging:
  level:
    root: ${LOG_LEVEL}
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  file:
    path: ./logs/${SPRING_PROFILE}
